version: 2
jobs:
  build:

    working_directory: ~/spring-sample-circleCI

    docker:
      - image: circleci/openjdk:11-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: spring-sample-circleCI-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: spring-sample-circleCI-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/demo-0.0.1-SNAPSHOT.jar

  docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: docker-image
          command: |
            TAG=latest
            IMAGE=application_name
            docker build -t $IMAGE:$TAG .
            docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            docker tag $IMAGE:$TAG $DOCKER_REGISTRY/$IMAGE:$TAG
            docker push $DOCKER_REGISTRY/$IMAGE:$TAG