version: 2
jobs:
  build:

    working_directory: /tmp/circleci

    docker:
      - image: circleci/openjdk:11-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: spring-sample-circleCI-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: spring-sample-circleCI-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          root: spring-sample-circleCI
          path:
            - target/demo-0.0.1-SNAPSHOT.jar
            - "Dockerfile"

  docker-image:
    working_directory: /tmp/circleci

    steps:

      - setup_remote_docker

      - attach_workspace:
          at: /tmp/circleci/spring-sample-circleCI

      - run:
          name: docker-image
          command: |
            TAG=latest
            IMAGE=demo
            docker build -t $IMAGE:$TAG .
            docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            docker tag $IMAGE:$TAG $DOCKER_REGISTRY/$IMAGE:$TAG
            docker push $DOCKER_REGISTRY/$IMAGE:$TAG

workflows:
  version: 2
  build_and_docker:
    jobs:
      - build
      - docker-image:
          requires:
            - build
          filters:
            branches:
              only: master